CREATE TABLE `tbl_registration` (
  `userId` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `firstname` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `lastname` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `username` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `password` VARCHAR(256) NULL DEFAULT NULL COMMENT '',
  `isloggedin` TINYINT(4) NULL COMMENT '',
  PRIMARY KEY (`userId`)  COMMENT '');